version: '3'

services:
  mysql:
    volumes:
      - ./data_mysql:/var/lib/mysql
    tty: true
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: secrethome
      TZ: Asia/Tokyo
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always

  nginx:
    volumes:
      - ./data_files:/data_files
    tty: true
    ports:
      - '61132:60132'
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    environment:
      TZ: Asia/Tokyo
    restart: always

  backend:
    volumes:
      - ./data_files:/backend/data_files
    tty: true
    ports:
      - '61133:60133'
    build:
      context: ./
      dockerfile: ./docker/backend/product/Dockerfile
    working_dir: /backend
    environment:
      TZ: Asia/Tokyo
    command: /backend/secrethome-back
    depends_on:
      - mysql

  web:
    volumes:
      - ./data_files:/data_files
      - ./next_app:/next_app
      - ./backend/proto:/next_app/proto
      - /next_app/node_modules
    tty: true
    ports:
      - '61131:3000'
    build:
      context: ./
      dockerfile: ./next_app/Dockerfile
    working_dir: /next_app
    environment:
      TZ: Asia/Tokyo
    entrypoint: sh -c "npm run build && npm run start"
    depends_on:
      - mysql
      - nginx
    restart: always