name: build-test

on: push

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: next_app

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Check cache node_modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        with:
          path: ./next_app/node_modules
          key: ${{ runner.os }}-build-front-cache-node-modules-${{ hashFiles('./next_app/package-lock.json') }}

      - name: Run npm ci
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: test ls
        run: ls -la

      - name: Build frontend
        run: npm run build

  build-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend/src

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v4

      - name: Run go mod download
        run: go mod download

      - name: Build backend
        run: go build -o ../



